Added streamlit ui interface file
CristhianRF24/enterprise-chat pull request #28
Opened 2024-10-23 14:53 UTC by BelenA25

2024-10-23 21:16 UTC, MartinArispeRiveros requested changes

2024-10-23 21:16 UTC, MartinArispeRiveros commented on app/streamlit/app.py
> +        endpoint = "http://127.0.0.1:8000/generate_sparql/" if st.session_state.use_knowledge_graph else "http://127.0.0.1:8000/generate_sql/"
@BelenA25 please modify the base url to use envdot please to manage differents urls

2024-10-25 12:49 UTC, CristhianRF24 approved these changes

2024-10-25 12:49 UTC, CristhianRF24 commented on requirements.txt
> +streamlit-toggle-switch
resolve your conflict

2024-10-25 13:15 UTC, merged